import json, os, sqlite3
from datetime import date

ROOT=os.path.dirname(os.path.abspath(__file__))
DB=os.path.join(os.path.dirname(ROOT),'V2.0.13-source','data','maturity.db')
OUT=os.path.join(ROOT,'v1.6')
db=sqlite3.connect(DB)
rows=[json.loads(x[0]) for x in db.execute('select payload from capabilities order by rowid')]
db.close()
for r in rows:
    r['planMonth']=(r.get('due') or '')[:7] if not int(r.get('achieved') or 0) else ''
    r['status']='已达成' if int(r.get('achieved') or 0) else ('已计划' if r['planMonth'] else '未计划')
payload=json.dumps({'version':'V2.0.13','generated':date.today().isoformat(),'rows':rows},ensure_ascii=False).replace('</','<\\/')
css='*{box-sizing:border-box}body{margin:0;background:#f5f7fa;color:#182b49;font:14px Arial,"Microsoft YaHei",sans-serif}main{max-width:1180px;margin:auto;padding:24px}.hero,.panel{background:#fff;border:1px solid #d8e0ea;border-radius:8px;padding:22px}.hero{background:#17365d;color:#fff;border:0}.hero h1{margin:0 0 6px;font-size:26px}.hero p{margin:4px 0;color:#dbeafe}.note{margin-top:13px;padding:9px 12px;background:#ffffff18;border-left:3px solid #79b8ff}.controls{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin:16px 0}.controls label{display:block;color:#65758b;font-size:12px}.controls select,.controls input{width:100%;padding:8px;margin-top:4px;border:1px solid #d8e0ea;border-radius:4px;background:white}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:10px 8px;border-bottom:1px solid #d8e0ea;text-align:left}th{background:#182b49;color:white}tr:nth-child(even){background:#f8fafc}.tag{padding:3px 7px;border-radius:4px;font-size:12px}.done{background:#d5f5e8;color:#086044}.planned{background:#fff1c2;color:#7a4d00}.empty{padding:24px;text-align:center;color:#65758b}.footer{margin-top:14px;color:#65758b;font-size:12px}@media(max-width:700px){main{padding:12px}.controls{grid-template-columns:1fr}.hero h1{font-size:22px}table{display:block;overflow:auto;white-space:nowrap}}'
html=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>成熟度达成情况·极简计划表</title><style>{css}</style></head><body><main><section class="hero"><h1>成熟度达成情况 · 极简计划表</h1><p>v1.6 · 基于 V2.0.13 能力数据的独立报告 · {date.today().isoformat()}</p><div class="note">当前已达成与计划预测分开展示；计划完成月按 YYYY-MM 填写，不修改 V2.0.13 实际达成数据。目标月份内预测达成 = 当前已达成 + 计划月不晚于目标月份的能力项。</div></section><section class="controls"><div><label>科组</label><select id="team"><option value="all">全部科组</option></select></div><div><label>领域</label><select id="domain"><option value="all">全部领域</option></select></div><div><label>目标月份</label><input id="month" type="month" value="2026-10"></div></section><section class="panel"><table><thead><tr><th>科组</th><th>部门</th><th>业务线</th><th>领域</th><th>评估维度</th><th>等级</th><th>当前达成</th><th>计划完成月</th><th>目标月预测</th><th>状态</th></tr></thead><tbody id="body"></tbody></table></section><p class="footer">数据源：V2.0.13 maturity.db（只读）；本版为极简展示原型，旧版本与正式版均未覆盖。</p></main><script>const P={payload},rows=P.rows,$=id=>document.getElementById(id);const teams=[...new Set(rows.map(r=>r.team).filter(Boolean))].sort(),domains=[...new Set(rows.map(r=>r.domain).filter(Boolean))].sort();$('team').innerHTML+='<option>'+teams.join('</option><option>')+'</option>';$('domain').innerHTML+='<option>'+domains.join('</option><option>')+'</option>';function render(){{const t=$('team').value,d=$('domain').value,m=$('month').value||'9999-12';const rs=rows.filter(r=>(t==='all'||r.team===t)&&(d==='all'||r.domain===d));$('body').innerHTML=rs.length?rs.map(r=>{{const actual=Number(r.achieved||0)===1,pred=actual||(!actual&&r.planMonth&&r.planMonth<=m);return`<tr><td>${{r.team||'-'}}</td><td>${{r.dept||'-'}}</td><td>${{r.org?.split('：')[0]||'-'}}</td><td>${{r.domain||'-'}}</td><td>${{r.dimension||'-'}}</td><td>${{r.level||'-'}}</td><td>${{actual?'是':'否'}}</td><td>${{r.planMonth||'未计划'}}</td><td>${{pred?'是':'否'}}</td><td><span class="tag ${{actual?'done':r.planMonth?'planned':''}}">${{actual?'已达成':r.planMonth?'已计划':'未计划'}}</span></td></tr>`}}).join(''):'<tr><td colspan="10" class="empty">当前筛选无能力项</td></tr>'}}$('team').onchange=render;$('domain').onchange=render;$('month').onchange=render;render();</script></body></html>'''
os.makedirs(OUT,exist_ok=True)
with open(os.path.join(OUT,'成熟度达成情况-极简计划表.html'),'w',encoding='utf-8') as f:f.write(html)
print(os.path.join(OUT,'成熟度达成情况-极简计划表.html'))
