import json, os, sqlite3
from datetime import date
ROOT=os.path.dirname(os.path.abspath(__file__)); DB=os.path.join(os.path.dirname(ROOT),'V2.0.13-source','data','maturity.db'); OUT=os.path.join(ROOT,'v1.8')
db=sqlite3.connect(DB); rows=[json.loads(x[0]) for x in db.execute('select payload from capabilities order by rowid')]; db.close()
for r in rows:
    r['planMonth']=(r.get('due') or '')[:7] if not int(r.get('achieved') or 0) else ''
blob=json.dumps({'version':'V2.0.13','generated':date.today().isoformat(),'rows':rows},ensure_ascii=False).replace('</','<\\/')
head=['id','org','domain','owner','dimension','sub','level','stage','digital','description','dept','team','delivered','achieved','due','planMonth','predicted','status']
labels=['ID','组织','领域','Owner','评估维度','细分能力','年度等级','年度目标','数字化验收','能力建设内容','部门','科组','是否已交付','当前达成','预计交付日期','计划完成月','目标月预测达成','状态']
style='body{font:14px Arial,"Microsoft YaHei";margin:0;background:#f5f7fa;color:#182b49}main{padding:24px;max-width:1500px;margin:auto}.hero,.panel{background:#fff;padding:20px;border:1px solid #d8e0ea;border-radius:8px}.hero{background:#17365d;color:#fff}.controls{display:flex;gap:12px;margin:16px 0}.controls>*{padding:8px;border:1px solid #d8e0ea;border-radius:4px}table{border-collapse:collapse;min-width:1500px;font-size:12px}th,td{padding:8px;border-bottom:1px solid #d8e0ea;white-space:nowrap;text-align:left}th{background:#182b49;color:#fff;position:sticky;top:0}.wrap{overflow:auto;max-height:75vh}.tag{padding:3px 6px;background:#fff1c2;border-radius:4px}.done{background:#d5f5e8}.muted{color:#65758b;font-size:12px}'
script=f'''const P={blob},rows=P.rows,$=x=>document.getElementById(x);const fields={json.dumps(head,ensure_ascii=False)},labels={json.dumps(labels,ensure_ascii=False)};const teams=[...new Set(rows.map(r=>r.team).filter(Boolean))].sort(),domains=[...new Set(rows.map(r=>r.domain).filter(Boolean))].sort();$('team').innerHTML+='<option>'+teams.join('</option><option>')+'</option>';$('domain').innerHTML+='<option>'+domains.join('</option><option>')+'</option>';function e(v){{return String(v??'-').replaceAll('&','&amp;').replaceAll('<','&lt;')}}function render(){{let t=$('team').value,d=$('domain').value,m=$('month').value||'12';let rs=rows.filter(r=>(t==='all'||r.team===t)&&(d==='all'||r.domain===d));$('body').innerHTML=rs.map(r=>{{let actual=+r.achieved===1,pred=actual||!!(r.planMonth&&r.planMonth.slice(-2)<=m);let vals={{...r,predicted:pred?'是':'否',status:actual?'已达成':r.planMonth?'已计划':'未计划'}};return '<tr>'+fields.map(k=>k==='planMonth'&&!actual?'<td><select onchange="this.closest(\'tr\').dataset.plan=this.value">'+['未计划',...Array.from({{length:12}},(_,i)=>String(i+1).padStart(2,'0')+'月')].map(x=>'<option>'+x+'</option>').join('')+'</select></td>':'<td>'+e(vals[k])+'</td>').join('')+'</tr>'}}).join('')||'<tr><td colspan="18" class="muted">当前筛选无能力项</td></tr>'}}$('team').onchange=render;$('domain').onchange=render;document.querySelectorAll('#month').forEach(x=>x.onchange=render);render();'''
html='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V2.0.13完整成熟度达成情况</title><style>'+style+'</style><main><section class="hero"><h1>V2.0.13 完整成熟度达成情况</h1><p>v1.8 独立只读副本 · '+date.today().isoformat()+'</p><p>保留 V2.0.13 全部成熟度字段；预计达成月仅管理 2026 年 1-12 月，不修改正式版本。</p></section><section class="controls"><select id="team"><option value="all">全部科组</option></select><select id="domain"><option value="all">全部领域</option></select><select id="month">'+''.join('<option>'+str(i).zfill(2)+'月</option>' for i in range(1,13))+'</select></section><section class="panel"><div class="wrap"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in labels)+'</tr></thead><tbody id="body"></tbody></table></div></section><p class="muted">预测达成=当前已达成+计划月不晚于目标月份的项；实际达成与预测达成互不影响。</p></main><script>'+script+'</script>'
os.makedirs(OUT,exist_ok=True)
with open(os.path.join(OUT,'V2.0.13-完整成熟度达成情况-v1.8.html'),'w',encoding='utf-8') as f:f.write(html)
print(os.path.join(OUT,'V2.0.13-完整成熟度达成情况-v1.8.html'))
