import { writeFileSync } from "node:fs";
const endpoint=process.argv[2]||"http://127.0.0.1:9225/json",width=Number(process.argv[3]||1600),height=Number(process.argv[4]||1450),shotPath=process.argv[5];
const pages=await(await fetch(endpoint)).json(),page=pages.find(x=>x.type==="page");if(!page)throw new Error("No Chrome page target found");
const socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true})});
let requestId=0;const pending=new Map();socket.addEventListener("message",event=>{const m=JSON.parse(event.data);if(!m.id||!pending.has(m.id))return;const h=pending.get(m.id);pending.delete(m.id);m.error?h.reject(new Error(m.error.message)):h.resolve(m.result)});
function call(method,params={}){const id=++requestId;socket.send(JSON.stringify({id,method,params}));return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))}
await call("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:width<600});await call("Page.reload",{ignoreCache:true});await call("Runtime.evaluate",{expression:"new Promise(r=>setTimeout(()=>requestAnimationFrame(()=>requestAnimationFrame(r)),250))",awaitPromise:true});
const expression=`(()=>{const visible=n=>{const s=getComputedStyle(n),r=n.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};const checked=[...document.querySelectorAll('.header,.locked,.section,.grid,.choice,.chart-wrap,.plot,.flow-wrap,.pipeline,.stage,.swim,.swim-row,.canvas,.canvas-step,.footer')].filter(visible);const overflow=checked.filter(n=>n.scrollWidth>n.clientWidth+3||n.scrollHeight>n.clientHeight+3).map(n=>({node:n.className,client:[n.clientWidth,n.clientHeight],scroll:[n.scrollWidth,n.scrollHeight]}));const external=[...document.querySelectorAll('[src],[href]')].map(n=>n.src||n.href).filter(v=>/^https?:/i.test(v));document.querySelector('[data-group="dept2"][data-choice="B"] .pick').click();document.querySelector('[data-group="flow2"][data-choice="C"] .pick').click();const saved=JSON.parse(localStorage.getItem('task21-style-selection-round2')||'{}');return{viewport:[innerWidth,innerHeight],body:[document.body.scrollWidth,document.body.scrollHeight],cards:document.querySelectorAll('[data-group]').length,overflow,external,saved}})()`;
const evaluated=await call("Runtime.evaluate",{expression,returnByValue:true}),report=evaluated.result.value;console.log(JSON.stringify(report,null,2));if(shotPath){const shot=await call("Page.captureScreenshot",{format:"png",fromSurface:true,captureBeyondViewport:false});writeFileSync(shotPath,Buffer.from(shot.data,"base64"))}socket.close();if(report.cards!==6||report.overflow.length||report.external.length||report.saved.dept2!=="B"||report.saved.flow2!=="C")process.exitCode=1;
